# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa39b00e46dfb89fd284892957dd18c174a3f11c8873783c7a3190b05fdb63236759858607be983515166b6679fd35d6b14932a6d1345f2b9cf3ea0f46c017ad

test:
  secret_key_base: ddd095b1be487d95470fc4bf2ddb408361943cddde98ce397b3dd765e748616908e91c60f3dbd34e9a412cc64ac6d636bdb2c380891a00f2f0fd23867325b090

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
